resources:

  - name: dotnetapp462repo
    type: gitRepo
    # replace dr_github with your GitHub integration name
    integration: dr_github
    versionTemplate:
      # replace with source code location (e.g. GitHub) where you cloned this
      # sample project.
      sourceName: devops-recipes/ci-docker-windows
      branch: master

jobs:

  - name: build_dotnetapp462
    type: runSh
    steps:
      - IN: dotnetapp462repo
      - TASK:
          name: docker_build_dotnetapp462
          runtime:
            container: false
          script:
            - pushd $env:DOTNETAPP462REPO_STATE/dotnetapp-4.6.2
            - docker build -t my-dotnet462-app .
            - docker run my-dotnet462-app
            - popd
